a=10
b=5
print("---------------------------------------")
print("ARITHMETIC OPERATION")
print("")
print("ADDITION")
print(a+b)
print("SUBTRACTION")

print(a-b)
print("MULTIPLICATION")
print(a*b)
print("EXPONENTIATION")
print(a**b)
print("DIVISION")
print(a/b)
print("FLOOR DIVISION")
print(a//b)
print("MODULUS")
print(a%b)
print("------------------------------------")
print("COMPARISON OPERATOR")
print("")   
print("EQUAL TO")
print(a==b)         
print("NOT EQUAL TO")
print(a!=b)
print("GREATER THAN")   
print(a>b)
print("LESS THAN")
print(a<b)
print("GREATER THAN OR EQUAL TO")
print(a>=b) 
print("LESS THAN OR EQUAL TO")
print(a<=b) 
print("------------------------------------")
print("LOGICAL OPERATOR")
print("")       
print("AND")
print(a>5 and b<10)
print("OR")
print(a>5 or b>10)
print("NOT")
print(not(a>5 and b<10))
print("------------------------------------")
print("ASSIGNMENT OPERATOR")
print("")   
print("equals to ")
print(a)
print("ADDITION ASSIGNMENT")
a+=5
print(a)
print("SUBTRACTION ASSIGNMENT")
a-=5
print(a)
print("MULTIPLICATION ASSIGNMENT")
a*=5
print(a)
print("DIVISION ASSIGNMENT")
a/=5
print(a)
print("EXPONENTIATION ASSIGNMENT")
a**=5
print(a)
print("FLOOR DIVISION ASSIGNMENT")
a//=5
print(a)
print("MODULUS ASSIGNMENT")
a%=5
print(a)
print("------------------------------------")
print("MEMBERSHIP OPERATOR")
print("")       
print("IN")
print(5 in [1, 2, 3, 4, 5])
print("NOT IN")
print(6 not in [1, 2, 3, 4, 5])
print("------------------------------------") 
print("IDENTITY OPERATOR")
print("")   
print("IS")
print(a is b)
print("IS NOT")
print(a is not b)
print("------------------------------------")
print("BITWISE OPERATOR")
print("")
a = 10
b = 5
print("BITWISE AND")
print(a & b)
print("BITWISE OR")
print(a | b)
print("BITWISE XOR")
print(a ^ b)
print("BITWISE NOT")
print(~a)
print("LEFT SHIFT")
print(a << 1)
print("RIGHT SHIFT")
print(a >> 1)
print("------------------------------------")